# -*- coding: utf-8 -*-
"""MachineLearningModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CBzBPwq4ht8av6FT9wvf9JlSd-XRXUK8
"""

!pip install streamlit pyngrok -q

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("student_data.csv.zip")

df.head()

df.info()

df.isnull().sum()

plt.figure(figsize=(8,5))
sns.histplot(df["math score"], bins=20)
plt.title("Math Score Distribution")
plt.show()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["gender"] = le.fit_transform(df["gender"])
df["lunch"] = le.fit_transform(df["lunch"])
df["test preparation course"] = le.fit_transform(df["test preparation course"])

X = df[[
    "gender",
    "reading score",
    "writing score",
    "lunch",
    "test preparation course"
]]

y = df["math score"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

print("Model Trained Successfully")

predictions = model.predict(X_test)

predictions[:5]

from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("Mean Absolute Error:", mae)
print("R2 Score:", r2)

import pickle

pickle.dump(model, open("model.pkl", "wb"))

print("Model Saved")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pickle
# import numpy as np
# 
# # Load model
# model = pickle.load(open("model.pkl", "rb"))
# 
# st.title("🎓 Student Performance Prediction System")
# 
# gender = st.selectbox("Gender", ["Male", "Female"])
# reading = st.number_input("Reading Score", 0, 100)
# writing = st.number_input("Writing Score", 0, 100)
# lunch = st.selectbox("Lunch Type", ["Standard", "Free"])
# prep = st.selectbox("Test Preparation", ["Completed", "None"])
# 
# # Encoding
# gender = 1 if gender == "Male" else 0
# lunch = 1 if lunch == "Standard" else 0
# prep = 1 if prep == "Completed" else 0
# 
# if st.button("Predict Math Score"):
# 
#     features = np.array([[gender, reading, writing, lunch, prep]])
# 
#     prediction = model.predict(features)
# 
#     st.success(f"Predicted Math Score: {prediction[0]:.2f}")

!streamlit run app.py &>/content/logs.txt &

from pyngrok import ngrok

public_url = ngrok.connect(8501)

print(public_url)

import pandas as pd
import os

filename = os.listdir()[1]

print("Detected File:", filename)

df = pd.read_csv(filename)

df.head()

!ngrok config add-authtoken YOUR_NGROK_TOKEN

!npm install localtunnel

!streamlit run app.py &>/content/logs.txt &

!npx localtunnel --port 8501

from google.colab import files

files.download("app.py")
files.download("model.pkl")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# 
# pandas
# numpy
# matplotlib
# seaborn
# scikit-learn
# streamlit
# pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile README.md
# 
# # Student Performance Prediction System
# 
# ## Overview
# Machine learning project that predicts student math scores.
# 
# ## Technologies Used
# - Python
# - Pandas
# - Scikit-learn
# - Streamlit
# 
# ## Features
# - Student score prediction
# - Data visualization
# - ML model training
# - Streamlit deployment
# 
# ## Run Project
# 
# streamlit run app.py